apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: db-volume
  accessModes:
  - ReadWriteMany
  #- ReadWriteOncePod  # https://kubernetes.io/blog/2021/09/13/read-write-once-pod-access-mode-alpha/