apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db
spec:
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: nfs-db-volume
  accessModes:
  - ReadWriteMany
  #- ReadWriteOncePod  # https://kubernetes.io/blog/2021/09/13/read-write-once-pod-access-mode-alpha/