apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  externalIPs:
  - 192.168.1.100
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
    targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.122.103