apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    volume: db-volume
spec:
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.122.10
    path: "/mnt/nfs/database"
  accessModes:
  - ReadWriteMany