apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-worker3
  labels:
    local-pvname: local-pv-worker3
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-class
  local:
    path: /mnt/local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-mongo-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage-class
  selector:
    matchLabels:
      local-pvname: local-pv-worker3