apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: message-queue
    component: consumer
    lab.name: job.work-queue
  name: consumers
spec:
  parallelism: 3
  template:
    metadata:
      labels:
        app: message-queue
        component: consumer
        lab.name: job.work-queue
    spec:
      containers:
      - name: worker
        image: "gcr.io/kuar-demo/kuard-amd64:1"
        imagePullPolicy: Always
        args:
        - "--keygen-enable"
        - "--keygen-exit-on-complete"
        - "--keygen-memq-server=http://queue:8080/memq/server"
        - "--keygen-memq-queue=keygen"
      restartPolicy: OnFailure